[[CURRENCIES]]
code="PHOTON"
issuer="GBUMIO5G77562NFZZVMKMAUQL3CCZOGTGTUP6PVVUS2BM7U2WSPHOTON"
name="Photon"
desc="Photon entitles you to Reddit Community Points from the subreddit /r/Stellar, a new tool for creative control, allowing you to be awarded by your contributions and have a voice in making important governance decisions in the community. The symbol to represent a single unit is Î³ (the Greek letter gamma)."
conditions="Users earn Photon for contributing to /r/Stellar through posting, commenting, and moderating while using Reddit Redesign. Users need a SEP-0007 compatible wallet. Each week, 2 million Photon will be distributed."
image="https://photon.center/images/logo.png"


# Sample provision of using TOML for providing extra information to remove the need of server-side storage
# This allows to change the price of Special Membership or Badges without doing server-side modifications on Reddit
# Sample format is product_id="price of a product in community points"
[[COMMUNITY_POINTS]]
membership="1000" # Price of Special Membership, "membership" is the unique ID and 1000 PHOTON is the price
badge_11="100" # Price of a Badge, "badge_11" is the unique ID and 100 PHOTON is the price
badge_12="200" # Price of a Badge, "badge_12" is the unique ID and 200 PHOTON is the price
