[[CURRENCIES]]
code="PHOTON"
issuer="GBUMIO5G77562NFZZVMKMAUQL3CCZOGTGTUP6PVVUS2BM7U2WSPHOTON"
name="Photon"
desc="Photon entitles you to Reddit Community Points from the subreddit /r/Stellar, a new tool for creative control, allowing you to be awarded by your contributions and have a voice in making important governance decisions in the community."
conditions="Users earn points for contributing to /r/Stellar through posting, commenting, and moderating. Each week, 2M points will be distributed."
image="https://photon.center/images/photon.png"

